version: '3.9'

services:
  db:
    image: postgres:13-alpine3.17
    ports:
      - "5431:5430"
    environment:
      POSTGRES_USER: '***'
      POSTGRES_PASSWORD: '***'
      POSTGRES_DB: '***'
      TZ: 'Europe/Moscow'